# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ChanYu
tagline:          'A Jekyll theme'
description: >
  我是展佑，臺大心理系畢業，自學Ruby On Rails與JavaScript。希望有天能成
  為一位獨當一面的全端工程師與設計師。
baseurl:          /

author:
  name:           'Chan Yu Chen'
  url:            https://github.com/j0214ack

hiring:           Available for hiring
